export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_ALL_KATEGORI = 'GET_ALL_KATEGORI';
export const GET_ALL_KATEGORI_FAILED = 'GET_ALL_KATEGORI_FAILED';
export const ADD_KATEGORI = 'ADD_KATEGORI';
export const DELETE_KATEGORI = 'DELETE_KATEGORI';
export const UPDATE_KATEGORI = 'UPDATE_KATEGORI';
export const GET_KATEGORI_BY_ID = 'GET_KATEGORI_BY_ID';

export const GET_ALL_DATA = 'GET_ALL_DATA';
